### ISSUE TITLE
Issue running app after installing it.

### ISSUE THREAD

**Issue by Ursache420** [malisipi/NewFlow#5]
Installed the app through the provided installer, but once I start the app this error occurs every single time:

![image](https://github.com/malisipi/NewFlow/assets/166541862/7b14182c-87ff-43e1-a145-f62e01742b2c)

**Comment by malisipi** [comment]
Oh, it's an error that seems like about live captions. I will fix it.

**Comment by malisipi** [comment]
Latest commit (00268120c1a0aad7325494a53c31602f4b8be49e) should fix the issue

**Comment by Ursache420** [comment]
Yep, it's fixed now. Really cool client, looking forward to seeing more features!

**Comment by malisipi** [comment]
I am glad to hear that.
